#ifndef XPARAMETERS_H   /* prevent circular inclusions */
#define XPARAMETERS_H   /* by using protection macros */

/* Definitions for bus frequencies */
#define XPAR_CPU_M_AXI_DP_FREQ_HZ 100000000
/******************************************************************/

/* Canonical definitions for bus frequencies */
/******************************************************************/

#define XPAR_CPU_CORE_CLOCK_FREQ_HZ 100000000
#define XPAR_MICROBLAZE_CORE_CLOCK_FREQ_HZ 100000000

/******************************************************************/


/* Definitions for peripheral MICROBLAZE_0 */
#define XPAR_MICROBLAZE_0_ADDR_SIZE 32
#define XPAR_MICROBLAZE_0_ADDR_TAG_BITS 17
#define XPAR_MICROBLAZE_0_ALLOW_DCACHE_WR 1
#define XPAR_MICROBLAZE_0_ALLOW_ICACHE_WR 1
#define XPAR_MICROBLAZE_0_AREA_OPTIMIZED 0
#define XPAR_MICROBLAZE_0_ASYNC_INTERRUPT 1
#define XPAR_MICROBLAZE_0_ASYNC_WAKEUP 3
#define XPAR_MICROBLAZE_0_AVOID_PRIMITIVES 0
#define XPAR_MICROBLAZE_0_BASE_VECTORS 0x0000000000000000
#define XPAR_MICROBLAZE_0_BRANCH_TARGET_CACHE_SIZE 0
#define XPAR_MICROBLAZE_0_CACHE_BYTE_SIZE 8192
#define XPAR_MICROBLAZE_0_DADDR_SIZE 32
#define XPAR_MICROBLAZE_0_DATA_SIZE 32
#define XPAR_MICROBLAZE_0_DCACHE_ADDR_TAG 17
#define XPAR_MICROBLAZE_0_DCACHE_ALWAYS_USED 1
#define XPAR_MICROBLAZE_0_DCACHE_BASEADDR 0x00000000
#define XPAR_MICROBLAZE_0_DCACHE_BYTE_SIZE 8192
#define XPAR_MICROBLAZE_0_DCACHE_DATA_WIDTH 0
#define XPAR_MICROBLAZE_0_DCACHE_FORCE_TAG_LUTRAM 0
#define XPAR_MICROBLAZE_0_DCACHE_HIGHADDR 0x3FFFFFFF
#define XPAR_MICROBLAZE_0_DCACHE_LINE_LEN 4
#define XPAR_MICROBLAZE_0_DCACHE_USE_WRITEBACK 0
#define XPAR_MICROBLAZE_0_DCACHE_VICTIMS 0
#define XPAR_MICROBLAZE_0_DC_AXI_MON 0
#define XPAR_MICROBLAZE_0_DEBUG_COUNTER_WIDTH 32
#define XPAR_MICROBLAZE_0_DEBUG_ENABLED 1
#define XPAR_MICROBLAZE_0_DEBUG_EVENT_COUNTERS 5
#define XPAR_MICROBLAZE_0_DEBUG_EXTERNAL_TRACE 0
#define XPAR_MICROBLAZE_0_DEBUG_INTERFACE 0
#define XPAR_MICROBLAZE_0_DEBUG_LATENCY_COUNTERS 1
#define XPAR_MICROBLAZE_0_DEBUG_PROFILE_SIZE 0
#define XPAR_MICROBLAZE_0_DEBUG_TRACE_ASYNC_RESET 0
#define XPAR_MICROBLAZE_0_DEBUG_TRACE_SIZE 8192
#define XPAR_MICROBLAZE_0_DIV_ZERO_EXCEPTION 0
#define XPAR_MICROBLAZE_0_DP_AXI_MON 0
#define XPAR_MICROBLAZE_0_DYNAMIC_BUS_SIZING 0
#define XPAR_MICROBLAZE_0_D_AXI 1
#define XPAR_MICROBLAZE_0_D_LMB 1
#define XPAR_MICROBLAZE_0_D_LMB_MON 0
#define XPAR_MICROBLAZE_0_D_LMB_PROTOCOL 0
#define XPAR_MICROBLAZE_0_ECC_USE_CE_EXCEPTION 0
#define XPAR_MICROBLAZE_0_EDGE_IS_POSITIVE 1
#define XPAR_MICROBLAZE_0_ENABLE_DISCRETE_PORTS 0
#define XPAR_MICROBLAZE_0_ENDIANNESS 1
#define XPAR_MICROBLAZE_0_FAULT_TOLERANT 0
#define XPAR_MICROBLAZE_0_FPU_EXCEPTION 0
#define XPAR_MICROBLAZE_0_FREQ 100000000
#define XPAR_MICROBLAZE_0_FSL_EXCEPTION 0
#define XPAR_MICROBLAZE_0_FSL_LINKS 0
#define XPAR_MICROBLAZE_0_IADDR_SIZE 32
#define XPAR_MICROBLAZE_0_ICACHE_ALWAYS_USED 1
#define XPAR_MICROBLAZE_0_ICACHE_BASEADDR 0x00000000
#define XPAR_MICROBLAZE_0_ICACHE_DATA_WIDTH 0
#define XPAR_MICROBLAZE_0_ICACHE_FORCE_TAG_LUTRAM 0
#define XPAR_MICROBLAZE_0_ICACHE_HIGHADDR 0x3FFFFFFF
#define XPAR_MICROBLAZE_0_ICACHE_LINE_LEN 4
#define XPAR_MICROBLAZE_0_ICACHE_STREAMS 0
#define XPAR_MICROBLAZE_0_ICACHE_VICTIMS 0
#define XPAR_MICROBLAZE_0_IC_AXI_MON 0
#define XPAR_MICROBLAZE_0_ILL_OPCODE_EXCEPTION 0
#define XPAR_MICROBLAZE_0_IMPRECISE_EXCEPTIONS 0
#define XPAR_MICROBLAZE_0_INSTR_SIZE 32
#define XPAR_MICROBLAZE_0_INTERCONNECT 2
#define XPAR_MICROBLAZE_0_INTERRUPT_IS_EDGE 0
#define XPAR_MICROBLAZE_0_INTERRUPT_MON 0
#define XPAR_MICROBLAZE_0_IP_AXI_MON 0
#define XPAR_MICROBLAZE_0_I_AXI 0
#define XPAR_MICROBLAZE_0_I_LMB 1
#define XPAR_MICROBLAZE_0_I_LMB_MON 0
#define XPAR_MICROBLAZE_0_I_LMB_PROTOCOL 0
#define XPAR_MICROBLAZE_0_LMB_DATA_SIZE 32
#define XPAR_MICROBLAZE_0_LOCKSTEP_MASTER 0
#define XPAR_MICROBLAZE_0_LOCKSTEP_SELECT 0
#define XPAR_MICROBLAZE_0_LOCKSTEP_SLAVE 0
#define XPAR_MICROBLAZE_0_M0_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_0_M0_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_0_M1_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_0_M1_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_0_M2_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_0_M2_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_0_M3_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_0_M3_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_0_M4_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_0_M4_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_0_M5_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_0_M5_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_0_M6_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_0_M6_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_0_M7_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_0_M7_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_0_M8_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_0_M8_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_0_M9_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_0_M9_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_0_M10_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_0_M10_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_0_M11_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_0_M11_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_0_M12_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_0_M12_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_0_M13_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_0_M13_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_0_M14_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_0_M14_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_0_M15_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_0_M15_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_0_MMU_DTLB_SIZE 4
#define XPAR_MICROBLAZE_0_MMU_ITLB_SIZE 2
#define XPAR_MICROBLAZE_0_MMU_PRIVILEGED_INSTR 0
#define XPAR_MICROBLAZE_0_MMU_TLB_ACCESS 3
#define XPAR_MICROBLAZE_0_MMU_ZONES 16
#define XPAR_MICROBLAZE_0_M_AXI_DC_ADDR_WIDTH 32
#define XPAR_MICROBLAZE_0_M_AXI_DC_ARUSER_WIDTH 5
#define XPAR_MICROBLAZE_0_M_AXI_DC_AWUSER_WIDTH 5
#define XPAR_MICROBLAZE_0_M_AXI_DC_BUSER_WIDTH 1
#define XPAR_MICROBLAZE_0_M_AXI_DC_DATA_WIDTH 32
#define XPAR_MICROBLAZE_0_M_AXI_DC_EXCLUSIVE_ACCESS 0
#define XPAR_MICROBLAZE_0_M_AXI_DC_RUSER_WIDTH 1
#define XPAR_MICROBLAZE_0_M_AXI_DC_THREAD_ID_WIDTH 1
#define XPAR_MICROBLAZE_0_M_AXI_DC_USER_SIGNALS 0
#define XPAR_MICROBLAZE_0_M_AXI_DC_USER_VALUE 31
#define XPAR_MICROBLAZE_0_M_AXI_DC_WUSER_WIDTH 1
#define XPAR_MICROBLAZE_0_M_AXI_DP_ADDR_WIDTH 32
#define XPAR_MICROBLAZE_0_M_AXI_DP_DATA_WIDTH 32
#define XPAR_MICROBLAZE_0_M_AXI_DP_EXCLUSIVE_ACCESS 0
#define XPAR_MICROBLAZE_0_M_AXI_DP_THREAD_ID_WIDTH 1
#define XPAR_MICROBLAZE_0_M_AXI_D_BUS_EXCEPTION 0
#define XPAR_MICROBLAZE_0_M_AXI_IC_ADDR_WIDTH 32
#define XPAR_MICROBLAZE_0_M_AXI_IC_ARUSER_WIDTH 5
#define XPAR_MICROBLAZE_0_M_AXI_IC_AWUSER_WIDTH 5
#define XPAR_MICROBLAZE_0_M_AXI_IC_BUSER_WIDTH 1
#define XPAR_MICROBLAZE_0_M_AXI_IC_DATA_WIDTH 32
#define XPAR_MICROBLAZE_0_M_AXI_IC_RUSER_WIDTH 1
#define XPAR_MICROBLAZE_0_M_AXI_IC_THREAD_ID_WIDTH 1
#define XPAR_MICROBLAZE_0_M_AXI_IC_USER_SIGNALS 0
#define XPAR_MICROBLAZE_0_M_AXI_IC_USER_VALUE 31
#define XPAR_MICROBLAZE_0_M_AXI_IC_WUSER_WIDTH 1
#define XPAR_MICROBLAZE_0_M_AXI_IP_ADDR_WIDTH 32
#define XPAR_MICROBLAZE_0_M_AXI_IP_DATA_WIDTH 32
#define XPAR_MICROBLAZE_0_M_AXI_IP_THREAD_ID_WIDTH 1
#define XPAR_MICROBLAZE_0_M_AXI_I_BUS_EXCEPTION 0
#define XPAR_MICROBLAZE_0_NUMBER_OF_PC_BRK 1
#define XPAR_MICROBLAZE_0_NUMBER_OF_RD_ADDR_BRK 0
#define XPAR_MICROBLAZE_0_NUMBER_OF_WR_ADDR_BRK 0
#define XPAR_MICROBLAZE_0_NUM_SYNC_FF_CLK 2
#define XPAR_MICROBLAZE_0_NUM_SYNC_FF_CLK_DEBUG 2
#define XPAR_MICROBLAZE_0_NUM_SYNC_FF_CLK_IRQ 1
#define XPAR_MICROBLAZE_0_NUM_SYNC_FF_DBG_CLK 1
#define XPAR_MICROBLAZE_0_NUM_SYNC_FF_DBG_TRACE_CLK 2
#define XPAR_MICROBLAZE_0_OPCODE_0X0_ILLEGAL 0
#define XPAR_MICROBLAZE_0_OPTIMIZATION 0
#define XPAR_MICROBLAZE_0_PC_WIDTH 32
#define XPAR_MICROBLAZE_0_PIADDR_SIZE 32
#define XPAR_MICROBLAZE_0_PVR 0
#define XPAR_MICROBLAZE_0_PVR_USER1 0x00
#define XPAR_MICROBLAZE_0_PVR_USER2 0x00000000
#define XPAR_MICROBLAZE_0_RESET_MSR 0x00000000
#define XPAR_MICROBLAZE_0_RESET_MSR_BIP 0
#define XPAR_MICROBLAZE_0_RESET_MSR_DCE 0
#define XPAR_MICROBLAZE_0_RESET_MSR_EE 0
#define XPAR_MICROBLAZE_0_RESET_MSR_EIP 0
#define XPAR_MICROBLAZE_0_RESET_MSR_ICE 0
#define XPAR_MICROBLAZE_0_RESET_MSR_IE 0
#define XPAR_MICROBLAZE_0_S0_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_0_S0_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_0_S1_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_0_S1_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_0_S2_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_0_S2_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_0_S3_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_0_S3_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_0_S4_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_0_S4_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_0_S5_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_0_S5_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_0_S6_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_0_S6_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_0_S7_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_0_S7_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_0_S8_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_0_S8_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_0_S9_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_0_S9_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_0_S10_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_0_S10_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_0_S11_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_0_S11_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_0_S12_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_0_S12_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_0_S13_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_0_S13_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_0_S14_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_0_S14_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_0_S15_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_0_S15_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_0_SCO 0
#define XPAR_MICROBLAZE_0_TRACE 0
#define XPAR_MICROBLAZE_0_UNALIGNED_EXCEPTIONS 0
#define XPAR_MICROBLAZE_0_USE_BARREL 0
#define XPAR_MICROBLAZE_0_USE_BRANCH_TARGET_CACHE 0
#define XPAR_MICROBLAZE_0_USE_CONFIG_RESET 0
#define XPAR_MICROBLAZE_0_USE_DCACHE 0
#define XPAR_MICROBLAZE_0_USE_DIV 0
#define XPAR_MICROBLAZE_0_USE_EXTENDED_FSL_INSTR 0
#define XPAR_MICROBLAZE_0_USE_EXT_BRK 0
#define XPAR_MICROBLAZE_0_USE_EXT_NM_BRK 0
#define XPAR_MICROBLAZE_0_USE_FPU 0
#define XPAR_MICROBLAZE_0_USE_HW_MUL 0
#define XPAR_MICROBLAZE_0_USE_ICACHE 0
#define XPAR_MICROBLAZE_0_USE_INTERRUPT 0
#define XPAR_MICROBLAZE_0_USE_MMU 0
#define XPAR_MICROBLAZE_0_USE_MSR_INSTR 0
#define XPAR_MICROBLAZE_0_USE_NON_SECURE 0
#define XPAR_MICROBLAZE_0_USE_PCMP_INSTR 0
#define XPAR_MICROBLAZE_0_USE_REORDER_INSTR 1
#define XPAR_MICROBLAZE_0_USE_STACK_PROTECTION 0
#define XPAR_MICROBLAZE_0_COMPONENT_NAME design_1_microblaze_0_1
#define XPAR_MICROBLAZE_0_EDK_IPTYPE PROCESSOR
#define XPAR_MICROBLAZE_0_EDK_SPECIAL microblaze
#define XPAR_MICROBLAZE_0_G_TEMPLATE_LIST 0
#define XPAR_MICROBLAZE_0_G_USE_EXCEPTIONS 0

/******************************************************************/

#define XPAR_CPU_ID 0
#define XPAR_MICROBLAZE_ID 0
#define XPAR_MICROBLAZE_ADDR_SIZE 32
#define XPAR_MICROBLAZE_ADDR_TAG_BITS 17
#define XPAR_MICROBLAZE_ALLOW_DCACHE_WR 1
#define XPAR_MICROBLAZE_ALLOW_ICACHE_WR 1
#define XPAR_MICROBLAZE_AREA_OPTIMIZED 0
#define XPAR_MICROBLAZE_ASYNC_INTERRUPT 1
#define XPAR_MICROBLAZE_ASYNC_WAKEUP 3
#define XPAR_MICROBLAZE_AVOID_PRIMITIVES 0
#define XPAR_MICROBLAZE_BASE_VECTORS 0x0000000000000000
#define XPAR_MICROBLAZE_BRANCH_TARGET_CACHE_SIZE 0
#define XPAR_MICROBLAZE_CACHE_BYTE_SIZE 8192
#define XPAR_MICROBLAZE_DADDR_SIZE 32
#define XPAR_MICROBLAZE_DATA_SIZE 32
#define XPAR_MICROBLAZE_DCACHE_ADDR_TAG 17
#define XPAR_MICROBLAZE_DCACHE_ALWAYS_USED 1
#define XPAR_MICROBLAZE_DCACHE_BASEADDR 0x00000000
#define XPAR_MICROBLAZE_DCACHE_BYTE_SIZE 8192
#define XPAR_MICROBLAZE_DCACHE_DATA_WIDTH 0
#define XPAR_MICROBLAZE_DCACHE_FORCE_TAG_LUTRAM 0
#define XPAR_MICROBLAZE_DCACHE_HIGHADDR 0x3FFFFFFF
#define XPAR_MICROBLAZE_DCACHE_LINE_LEN 4
#define XPAR_MICROBLAZE_DCACHE_USE_WRITEBACK 0
#define XPAR_MICROBLAZE_DCACHE_VICTIMS 0
#define XPAR_MICROBLAZE_DC_AXI_MON 0
#define XPAR_MICROBLAZE_DEBUG_COUNTER_WIDTH 32
#define XPAR_MICROBLAZE_DEBUG_ENABLED 1
#define XPAR_MICROBLAZE_DEBUG_EVENT_COUNTERS 5
#define XPAR_MICROBLAZE_DEBUG_EXTERNAL_TRACE 0
#define XPAR_MICROBLAZE_DEBUG_INTERFACE 0
#define XPAR_MICROBLAZE_DEBUG_LATENCY_COUNTERS 1
#define XPAR_MICROBLAZE_DEBUG_PROFILE_SIZE 0
#define XPAR_MICROBLAZE_DEBUG_TRACE_ASYNC_RESET 0
#define XPAR_MICROBLAZE_DEBUG_TRACE_SIZE 8192
#define XPAR_MICROBLAZE_DIV_ZERO_EXCEPTION 0
#define XPAR_MICROBLAZE_DP_AXI_MON 0
#define XPAR_MICROBLAZE_DYNAMIC_BUS_SIZING 0
#define XPAR_MICROBLAZE_D_AXI 1
#define XPAR_MICROBLAZE_D_LMB 1
#define XPAR_MICROBLAZE_D_LMB_MON 0
#define XPAR_MICROBLAZE_D_LMB_PROTOCOL 0
#define XPAR_MICROBLAZE_ECC_USE_CE_EXCEPTION 0
#define XPAR_MICROBLAZE_EDGE_IS_POSITIVE 1
#define XPAR_MICROBLAZE_ENABLE_DISCRETE_PORTS 0
#define XPAR_MICROBLAZE_ENDIANNESS 1
#define XPAR_MICROBLAZE_FAULT_TOLERANT 0
#define XPAR_MICROBLAZE_FPU_EXCEPTION 0
#define XPAR_MICROBLAZE_FREQ 100000000
#define XPAR_MICROBLAZE_FSL_EXCEPTION 0
#define XPAR_MICROBLAZE_FSL_LINKS 0
#define XPAR_MICROBLAZE_IADDR_SIZE 32
#define XPAR_MICROBLAZE_ICACHE_ALWAYS_USED 1
#define XPAR_MICROBLAZE_ICACHE_BASEADDR 0x00000000
#define XPAR_MICROBLAZE_ICACHE_DATA_WIDTH 0
#define XPAR_MICROBLAZE_ICACHE_FORCE_TAG_LUTRAM 0
#define XPAR_MICROBLAZE_ICACHE_HIGHADDR 0x3FFFFFFF
#define XPAR_MICROBLAZE_ICACHE_LINE_LEN 4
#define XPAR_MICROBLAZE_ICACHE_STREAMS 0
#define XPAR_MICROBLAZE_ICACHE_VICTIMS 0
#define XPAR_MICROBLAZE_IC_AXI_MON 0
#define XPAR_MICROBLAZE_ILL_OPCODE_EXCEPTION 0
#define XPAR_MICROBLAZE_IMPRECISE_EXCEPTIONS 0
#define XPAR_MICROBLAZE_INSTR_SIZE 32
#define XPAR_MICROBLAZE_INTERCONNECT 2
#define XPAR_MICROBLAZE_INTERRUPT_IS_EDGE 0
#define XPAR_MICROBLAZE_INTERRUPT_MON 0
#define XPAR_MICROBLAZE_IP_AXI_MON 0
#define XPAR_MICROBLAZE_I_AXI 0
#define XPAR_MICROBLAZE_I_LMB 1
#define XPAR_MICROBLAZE_I_LMB_MON 0
#define XPAR_MICROBLAZE_I_LMB_PROTOCOL 0
#define XPAR_MICROBLAZE_LMB_DATA_SIZE 32
#define XPAR_MICROBLAZE_LOCKSTEP_MASTER 0
#define XPAR_MICROBLAZE_LOCKSTEP_SELECT 0
#define XPAR_MICROBLAZE_LOCKSTEP_SLAVE 0
#define XPAR_MICROBLAZE_M0_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_M0_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_M1_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_M1_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_M2_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_M2_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_M3_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_M3_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_M4_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_M4_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_M5_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_M5_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_M6_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_M6_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_M7_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_M7_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_M8_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_M8_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_M9_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_M9_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_M10_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_M10_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_M11_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_M11_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_M12_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_M12_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_M13_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_M13_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_M14_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_M14_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_M15_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_M15_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_MMU_DTLB_SIZE 4
#define XPAR_MICROBLAZE_MMU_ITLB_SIZE 2
#define XPAR_MICROBLAZE_MMU_PRIVILEGED_INSTR 0
#define XPAR_MICROBLAZE_MMU_TLB_ACCESS 3
#define XPAR_MICROBLAZE_MMU_ZONES 16
#define XPAR_MICROBLAZE_M_AXI_DC_ADDR_WIDTH 32
#define XPAR_MICROBLAZE_M_AXI_DC_ARUSER_WIDTH 5
#define XPAR_MICROBLAZE_M_AXI_DC_AWUSER_WIDTH 5
#define XPAR_MICROBLAZE_M_AXI_DC_BUSER_WIDTH 1
#define XPAR_MICROBLAZE_M_AXI_DC_DATA_WIDTH 32
#define XPAR_MICROBLAZE_M_AXI_DC_EXCLUSIVE_ACCESS 0
#define XPAR_MICROBLAZE_M_AXI_DC_RUSER_WIDTH 1
#define XPAR_MICROBLAZE_M_AXI_DC_THREAD_ID_WIDTH 1
#define XPAR_MICROBLAZE_M_AXI_DC_USER_SIGNALS 0
#define XPAR_MICROBLAZE_M_AXI_DC_USER_VALUE 31
#define XPAR_MICROBLAZE_M_AXI_DC_WUSER_WIDTH 1
#define XPAR_MICROBLAZE_M_AXI_DP_ADDR_WIDTH 32
#define XPAR_MICROBLAZE_M_AXI_DP_DATA_WIDTH 32
#define XPAR_MICROBLAZE_M_AXI_DP_EXCLUSIVE_ACCESS 0
#define XPAR_MICROBLAZE_M_AXI_DP_THREAD_ID_WIDTH 1
#define XPAR_MICROBLAZE_M_AXI_D_BUS_EXCEPTION 0
#define XPAR_MICROBLAZE_M_AXI_IC_ADDR_WIDTH 32
#define XPAR_MICROBLAZE_M_AXI_IC_ARUSER_WIDTH 5
#define XPAR_MICROBLAZE_M_AXI_IC_AWUSER_WIDTH 5
#define XPAR_MICROBLAZE_M_AXI_IC_BUSER_WIDTH 1
#define XPAR_MICROBLAZE_M_AXI_IC_DATA_WIDTH 32
#define XPAR_MICROBLAZE_M_AXI_IC_RUSER_WIDTH 1
#define XPAR_MICROBLAZE_M_AXI_IC_THREAD_ID_WIDTH 1
#define XPAR_MICROBLAZE_M_AXI_IC_USER_SIGNALS 0
#define XPAR_MICROBLAZE_M_AXI_IC_USER_VALUE 31
#define XPAR_MICROBLAZE_M_AXI_IC_WUSER_WIDTH 1
#define XPAR_MICROBLAZE_M_AXI_IP_ADDR_WIDTH 32
#define XPAR_MICROBLAZE_M_AXI_IP_DATA_WIDTH 32
#define XPAR_MICROBLAZE_M_AXI_IP_THREAD_ID_WIDTH 1
#define XPAR_MICROBLAZE_M_AXI_I_BUS_EXCEPTION 0
#define XPAR_MICROBLAZE_NUMBER_OF_PC_BRK 1
#define XPAR_MICROBLAZE_NUMBER_OF_RD_ADDR_BRK 0
#define XPAR_MICROBLAZE_NUMBER_OF_WR_ADDR_BRK 0
#define XPAR_MICROBLAZE_NUM_SYNC_FF_CLK 2
#define XPAR_MICROBLAZE_NUM_SYNC_FF_CLK_DEBUG 2
#define XPAR_MICROBLAZE_NUM_SYNC_FF_CLK_IRQ 1
#define XPAR_MICROBLAZE_NUM_SYNC_FF_DBG_CLK 1
#define XPAR_MICROBLAZE_NUM_SYNC_FF_DBG_TRACE_CLK 2
#define XPAR_MICROBLAZE_OPCODE_0X0_ILLEGAL 0
#define XPAR_MICROBLAZE_OPTIMIZATION 0
#define XPAR_MICROBLAZE_PC_WIDTH 32
#define XPAR_MICROBLAZE_PIADDR_SIZE 32
#define XPAR_MICROBLAZE_PVR 0
#define XPAR_MICROBLAZE_PVR_USER1 0x00
#define XPAR_MICROBLAZE_PVR_USER2 0x00000000
#define XPAR_MICROBLAZE_RESET_MSR 0x00000000
#define XPAR_MICROBLAZE_RESET_MSR_BIP 0
#define XPAR_MICROBLAZE_RESET_MSR_DCE 0
#define XPAR_MICROBLAZE_RESET_MSR_EE 0
#define XPAR_MICROBLAZE_RESET_MSR_EIP 0
#define XPAR_MICROBLAZE_RESET_MSR_ICE 0
#define XPAR_MICROBLAZE_RESET_MSR_IE 0
#define XPAR_MICROBLAZE_S0_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_S0_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_S1_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_S1_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_S2_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_S2_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_S3_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_S3_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_S4_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_S4_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_S5_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_S5_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_S6_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_S6_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_S7_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_S7_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_S8_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_S8_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_S9_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_S9_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_S10_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_S10_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_S11_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_S11_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_S12_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_S12_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_S13_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_S13_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_S14_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_S14_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_S15_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_S15_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_SCO 0
#define XPAR_MICROBLAZE_TRACE 0
#define XPAR_MICROBLAZE_UNALIGNED_EXCEPTIONS 0
#define XPAR_MICROBLAZE_USE_BARREL 0
#define XPAR_MICROBLAZE_USE_BRANCH_TARGET_CACHE 0
#define XPAR_MICROBLAZE_USE_CONFIG_RESET 0
#define XPAR_MICROBLAZE_USE_DCACHE 0
#define XPAR_MICROBLAZE_USE_DIV 0
#define XPAR_MICROBLAZE_USE_EXTENDED_FSL_INSTR 0
#define XPAR_MICROBLAZE_USE_EXT_BRK 0
#define XPAR_MICROBLAZE_USE_EXT_NM_BRK 0
#define XPAR_MICROBLAZE_USE_FPU 0
#define XPAR_MICROBLAZE_USE_HW_MUL 0
#define XPAR_MICROBLAZE_USE_ICACHE 0
#define XPAR_MICROBLAZE_USE_INTERRUPT 0
#define XPAR_MICROBLAZE_USE_MMU 0
#define XPAR_MICROBLAZE_USE_MSR_INSTR 0
#define XPAR_MICROBLAZE_USE_NON_SECURE 0
#define XPAR_MICROBLAZE_USE_PCMP_INSTR 0
#define XPAR_MICROBLAZE_USE_REORDER_INSTR 1
#define XPAR_MICROBLAZE_USE_STACK_PROTECTION 0
#define XPAR_MICROBLAZE_COMPONENT_NAME design_1_microblaze_0_1
#define XPAR_MICROBLAZE_EDK_IPTYPE PROCESSOR
#define XPAR_MICROBLAZE_EDK_SPECIAL microblaze
#define XPAR_MICROBLAZE_G_TEMPLATE_LIST 0
#define XPAR_MICROBLAZE_G_USE_EXCEPTIONS 0

/******************************************************************/

#define STDIN_BASEADDRESS 0x40600000
#define STDOUT_BASEADDRESS 0x40600000

/******************************************************************/

/* Platform specific definitions */
#define PLATFORM_MB
 
/* Definitions for sleep timer configuration */
#define XSLEEP_TIMER_IS_DEFAULT_TIMER
 
 
/******************************************************************/
/* Definitions for driver CONTROLLER */
#define XPAR_XCONTROLLER_NUM_INSTANCES 1

/* Definitions for peripheral CONTROLLER_0 */
#define XPAR_CONTROLLER_0_DEVICE_ID 0
#define XPAR_CONTROLLER_0_S_AXI_BUS_BUNDLE_BASEADDR 0x44A00000
#define XPAR_CONTROLLER_0_S_AXI_BUS_BUNDLE_HIGHADDR 0x44A0FFFF


/******************************************************************/

/* Canonical definitions for peripheral CONTROLLER_0 */
#define XPAR_XCONTROLLER_0_DEVICE_ID XPAR_CONTROLLER_0_DEVICE_ID
#define XPAR_XCONTROLLER_0_S_AXI_BUS_BUNDLE_BASEADDR 0x44A00000
#define XPAR_XCONTROLLER_0_S_AXI_BUS_BUNDLE_HIGHADDR 0x44A0FFFF


/******************************************************************/

/* Definitions for driver BRAM */
#define XPAR_XBRAM_NUM_INSTANCES 24U

/* Definitions for peripheral AXI_BRAM_CTRL_0 */
#define XPAR_AXI_BRAM_CTRL_0_DEVICE_ID 0U
#define XPAR_AXI_BRAM_CTRL_0_DATA_WIDTH 32U
#define XPAR_AXI_BRAM_CTRL_0_ECC 0U
#define XPAR_AXI_BRAM_CTRL_0_FAULT_INJECT 0U
#define XPAR_AXI_BRAM_CTRL_0_CE_FAILING_REGISTERS 0U
#define XPAR_AXI_BRAM_CTRL_0_UE_FAILING_REGISTERS 0U
#define XPAR_AXI_BRAM_CTRL_0_ECC_STATUS_REGISTERS 0U
#define XPAR_AXI_BRAM_CTRL_0_CE_COUNTER_WIDTH 0U
#define XPAR_AXI_BRAM_CTRL_0_ECC_ONOFF_REGISTER 0U
#define XPAR_AXI_BRAM_CTRL_0_ECC_ONOFF_RESET_VALUE 0U
#define XPAR_AXI_BRAM_CTRL_0_WRITE_ACCESS 0U
#define XPAR_AXI_BRAM_CTRL_0_S_AXI_BASEADDR 0xC0000000U
#define XPAR_AXI_BRAM_CTRL_0_S_AXI_HIGHADDR 0xC001FFFFU
#define XPAR_AXI_BRAM_CTRL_0_S_AXI_CTRL_BASEADDR 0xFFFFFFFFU  
#define XPAR_AXI_BRAM_CTRL_0_S_AXI_CTRL_HIGHADDR 0xFFFFFFFFU  


/* Definitions for peripheral AXI_BRAM_CTRL_1 */
#define XPAR_AXI_BRAM_CTRL_1_DEVICE_ID 1U
#define XPAR_AXI_BRAM_CTRL_1_DATA_WIDTH 32U
#define XPAR_AXI_BRAM_CTRL_1_ECC 0U
#define XPAR_AXI_BRAM_CTRL_1_FAULT_INJECT 0U
#define XPAR_AXI_BRAM_CTRL_1_CE_FAILING_REGISTERS 0U
#define XPAR_AXI_BRAM_CTRL_1_UE_FAILING_REGISTERS 0U
#define XPAR_AXI_BRAM_CTRL_1_ECC_STATUS_REGISTERS 0U
#define XPAR_AXI_BRAM_CTRL_1_CE_COUNTER_WIDTH 0U
#define XPAR_AXI_BRAM_CTRL_1_ECC_ONOFF_REGISTER 0U
#define XPAR_AXI_BRAM_CTRL_1_ECC_ONOFF_RESET_VALUE 0U
#define XPAR_AXI_BRAM_CTRL_1_WRITE_ACCESS 0U
#define XPAR_AXI_BRAM_CTRL_1_S_AXI_BASEADDR 0xC2000000U
#define XPAR_AXI_BRAM_CTRL_1_S_AXI_HIGHADDR 0xC201FFFFU
#define XPAR_AXI_BRAM_CTRL_1_S_AXI_CTRL_BASEADDR 0xFFFFFFFFU  
#define XPAR_AXI_BRAM_CTRL_1_S_AXI_CTRL_HIGHADDR 0xFFFFFFFFU  


/* Definitions for peripheral AXI_BRAM_CTRL_10 */
#define XPAR_AXI_BRAM_CTRL_10_DEVICE_ID 2U
#define XPAR_AXI_BRAM_CTRL_10_DATA_WIDTH 32U
#define XPAR_AXI_BRAM_CTRL_10_ECC 0U
#define XPAR_AXI_BRAM_CTRL_10_FAULT_INJECT 0U
#define XPAR_AXI_BRAM_CTRL_10_CE_FAILING_REGISTERS 0U
#define XPAR_AXI_BRAM_CTRL_10_UE_FAILING_REGISTERS 0U
#define XPAR_AXI_BRAM_CTRL_10_ECC_STATUS_REGISTERS 0U
#define XPAR_AXI_BRAM_CTRL_10_CE_COUNTER_WIDTH 0U
#define XPAR_AXI_BRAM_CTRL_10_ECC_ONOFF_REGISTER 0U
#define XPAR_AXI_BRAM_CTRL_10_ECC_ONOFF_RESET_VALUE 0U
#define XPAR_AXI_BRAM_CTRL_10_WRITE_ACCESS 0U
#define XPAR_AXI_BRAM_CTRL_10_S_AXI_BASEADDR 0xD4000000U
#define XPAR_AXI_BRAM_CTRL_10_S_AXI_HIGHADDR 0xD401FFFFU
#define XPAR_AXI_BRAM_CTRL_10_S_AXI_CTRL_BASEADDR 0xFFFFFFFFU  
#define XPAR_AXI_BRAM_CTRL_10_S_AXI_CTRL_HIGHADDR 0xFFFFFFFFU  


/* Definitions for peripheral AXI_BRAM_CTRL_11 */
#define XPAR_AXI_BRAM_CTRL_11_DEVICE_ID 3U
#define XPAR_AXI_BRAM_CTRL_11_DATA_WIDTH 32U
#define XPAR_AXI_BRAM_CTRL_11_ECC 0U
#define XPAR_AXI_BRAM_CTRL_11_FAULT_INJECT 0U
#define XPAR_AXI_BRAM_CTRL_11_CE_FAILING_REGISTERS 0U
#define XPAR_AXI_BRAM_CTRL_11_UE_FAILING_REGISTERS 0U
#define XPAR_AXI_BRAM_CTRL_11_ECC_STATUS_REGISTERS 0U
#define XPAR_AXI_BRAM_CTRL_11_CE_COUNTER_WIDTH 0U
#define XPAR_AXI_BRAM_CTRL_11_ECC_ONOFF_REGISTER 0U
#define XPAR_AXI_BRAM_CTRL_11_ECC_ONOFF_RESET_VALUE 0U
#define XPAR_AXI_BRAM_CTRL_11_WRITE_ACCESS 0U
#define XPAR_AXI_BRAM_CTRL_11_S_AXI_BASEADDR 0xD6000000U
#define XPAR_AXI_BRAM_CTRL_11_S_AXI_HIGHADDR 0xD601FFFFU
#define XPAR_AXI_BRAM_CTRL_11_S_AXI_CTRL_BASEADDR 0xFFFFFFFFU  
#define XPAR_AXI_BRAM_CTRL_11_S_AXI_CTRL_HIGHADDR 0xFFFFFFFFU  


/* Definitions for peripheral AXI_BRAM_CTRL_12 */
#define XPAR_AXI_BRAM_CTRL_12_DEVICE_ID 4U
#define XPAR_AXI_BRAM_CTRL_12_DATA_WIDTH 32U
#define XPAR_AXI_BRAM_CTRL_12_ECC 0U
#define XPAR_AXI_BRAM_CTRL_12_FAULT_INJECT 0U
#define XPAR_AXI_BRAM_CTRL_12_CE_FAILING_REGISTERS 0U
#define XPAR_AXI_BRAM_CTRL_12_UE_FAILING_REGISTERS 0U
#define XPAR_AXI_BRAM_CTRL_12_ECC_STATUS_REGISTERS 0U
#define XPAR_AXI_BRAM_CTRL_12_CE_COUNTER_WIDTH 0U
#define XPAR_AXI_BRAM_CTRL_12_ECC_ONOFF_REGISTER 0U
#define XPAR_AXI_BRAM_CTRL_12_ECC_ONOFF_RESET_VALUE 0U
#define XPAR_AXI_BRAM_CTRL_12_WRITE_ACCESS 0U
#define XPAR_AXI_BRAM_CTRL_12_S_AXI_BASEADDR 0xD8000000U
#define XPAR_AXI_BRAM_CTRL_12_S_AXI_HIGHADDR 0xD801FFFFU
#define XPAR_AXI_BRAM_CTRL_12_S_AXI_CTRL_BASEADDR 0xFFFFFFFFU  
#define XPAR_AXI_BRAM_CTRL_12_S_AXI_CTRL_HIGHADDR 0xFFFFFFFFU  


/* Definitions for peripheral AXI_BRAM_CTRL_13 */
#define XPAR_AXI_BRAM_CTRL_13_DEVICE_ID 5U
#define XPAR_AXI_BRAM_CTRL_13_DATA_WIDTH 32U
#define XPAR_AXI_BRAM_CTRL_13_ECC 0U
#define XPAR_AXI_BRAM_CTRL_13_FAULT_INJECT 0U
#define XPAR_AXI_BRAM_CTRL_13_CE_FAILING_REGISTERS 0U
#define XPAR_AXI_BRAM_CTRL_13_UE_FAILING_REGISTERS 0U
#define XPAR_AXI_BRAM_CTRL_13_ECC_STATUS_REGISTERS 0U
#define XPAR_AXI_BRAM_CTRL_13_CE_COUNTER_WIDTH 0U
#define XPAR_AXI_BRAM_CTRL_13_ECC_ONOFF_REGISTER 0U
#define XPAR_AXI_BRAM_CTRL_13_ECC_ONOFF_RESET_VALUE 0U
#define XPAR_AXI_BRAM_CTRL_13_WRITE_ACCESS 0U
#define XPAR_AXI_BRAM_CTRL_13_S_AXI_BASEADDR 0xDA000000U
#define XPAR_AXI_BRAM_CTRL_13_S_AXI_HIGHADDR 0xDA01FFFFU
#define XPAR_AXI_BRAM_CTRL_13_S_AXI_CTRL_BASEADDR 0xFFFFFFFFU  
#define XPAR_AXI_BRAM_CTRL_13_S_AXI_CTRL_HIGHADDR 0xFFFFFFFFU  


/* Definitions for peripheral AXI_BRAM_CTRL_14 */
#define XPAR_AXI_BRAM_CTRL_14_DEVICE_ID 6U
#define XPAR_AXI_BRAM_CTRL_14_DATA_WIDTH 32U
#define XPAR_AXI_BRAM_CTRL_14_ECC 0U
#define XPAR_AXI_BRAM_CTRL_14_FAULT_INJECT 0U
#define XPAR_AXI_BRAM_CTRL_14_CE_FAILING_REGISTERS 0U
#define XPAR_AXI_BRAM_CTRL_14_UE_FAILING_REGISTERS 0U
#define XPAR_AXI_BRAM_CTRL_14_ECC_STATUS_REGISTERS 0U
#define XPAR_AXI_BRAM_CTRL_14_CE_COUNTER_WIDTH 0U
#define XPAR_AXI_BRAM_CTRL_14_ECC_ONOFF_REGISTER 0U
#define XPAR_AXI_BRAM_CTRL_14_ECC_ONOFF_RESET_VALUE 0U
#define XPAR_AXI_BRAM_CTRL_14_WRITE_ACCESS 0U
#define XPAR_AXI_BRAM_CTRL_14_S_AXI_BASEADDR 0xDC000000U
#define XPAR_AXI_BRAM_CTRL_14_S_AXI_HIGHADDR 0xDC01FFFFU
#define XPAR_AXI_BRAM_CTRL_14_S_AXI_CTRL_BASEADDR 0xFFFFFFFFU  
#define XPAR_AXI_BRAM_CTRL_14_S_AXI_CTRL_HIGHADDR 0xFFFFFFFFU  


/* Definitions for peripheral AXI_BRAM_CTRL_15 */
#define XPAR_AXI_BRAM_CTRL_15_DEVICE_ID 7U
#define XPAR_AXI_BRAM_CTRL_15_DATA_WIDTH 32U
#define XPAR_AXI_BRAM_CTRL_15_ECC 0U
#define XPAR_AXI_BRAM_CTRL_15_FAULT_INJECT 0U
#define XPAR_AXI_BRAM_CTRL_15_CE_FAILING_REGISTERS 0U
#define XPAR_AXI_BRAM_CTRL_15_UE_FAILING_REGISTERS 0U
#define XPAR_AXI_BRAM_CTRL_15_ECC_STATUS_REGISTERS 0U
#define XPAR_AXI_BRAM_CTRL_15_CE_COUNTER_WIDTH 0U
#define XPAR_AXI_BRAM_CTRL_15_ECC_ONOFF_REGISTER 0U
#define XPAR_AXI_BRAM_CTRL_15_ECC_ONOFF_RESET_VALUE 0U
#define XPAR_AXI_BRAM_CTRL_15_WRITE_ACCESS 0U
#define XPAR_AXI_BRAM_CTRL_15_S_AXI_BASEADDR 0xDE000000U
#define XPAR_AXI_BRAM_CTRL_15_S_AXI_HIGHADDR 0xDE01FFFFU
#define XPAR_AXI_BRAM_CTRL_15_S_AXI_CTRL_BASEADDR 0xFFFFFFFFU  
#define XPAR_AXI_BRAM_CTRL_15_S_AXI_CTRL_HIGHADDR 0xFFFFFFFFU  


/* Definitions for peripheral AXI_BRAM_CTRL_16 */
#define XPAR_AXI_BRAM_CTRL_16_DEVICE_ID 8U
#define XPAR_AXI_BRAM_CTRL_16_DATA_WIDTH 32U
#define XPAR_AXI_BRAM_CTRL_16_ECC 0U
#define XPAR_AXI_BRAM_CTRL_16_FAULT_INJECT 0U
#define XPAR_AXI_BRAM_CTRL_16_CE_FAILING_REGISTERS 0U
#define XPAR_AXI_BRAM_CTRL_16_UE_FAILING_REGISTERS 0U
#define XPAR_AXI_BRAM_CTRL_16_ECC_STATUS_REGISTERS 0U
#define XPAR_AXI_BRAM_CTRL_16_CE_COUNTER_WIDTH 0U
#define XPAR_AXI_BRAM_CTRL_16_ECC_ONOFF_REGISTER 0U
#define XPAR_AXI_BRAM_CTRL_16_ECC_ONOFF_RESET_VALUE 0U
#define XPAR_AXI_BRAM_CTRL_16_WRITE_ACCESS 0U
#define XPAR_AXI_BRAM_CTRL_16_S_AXI_BASEADDR 0xE0000000U
#define XPAR_AXI_BRAM_CTRL_16_S_AXI_HIGHADDR 0xE001FFFFU
#define XPAR_AXI_BRAM_CTRL_16_S_AXI_CTRL_BASEADDR 0xFFFFFFFFU  
#define XPAR_AXI_BRAM_CTRL_16_S_AXI_CTRL_HIGHADDR 0xFFFFFFFFU  


/* Definitions for peripheral AXI_BRAM_CTRL_17 */
#define XPAR_AXI_BRAM_CTRL_17_DEVICE_ID 9U
#define XPAR_AXI_BRAM_CTRL_17_DATA_WIDTH 32U
#define XPAR_AXI_BRAM_CTRL_17_ECC 0U
#define XPAR_AXI_BRAM_CTRL_17_FAULT_INJECT 0U
#define XPAR_AXI_BRAM_CTRL_17_CE_FAILING_REGISTERS 0U
#define XPAR_AXI_BRAM_CTRL_17_UE_FAILING_REGISTERS 0U
#define XPAR_AXI_BRAM_CTRL_17_ECC_STATUS_REGISTERS 0U
#define XPAR_AXI_BRAM_CTRL_17_CE_COUNTER_WIDTH 0U
#define XPAR_AXI_BRAM_CTRL_17_ECC_ONOFF_REGISTER 0U
#define XPAR_AXI_BRAM_CTRL_17_ECC_ONOFF_RESET_VALUE 0U
#define XPAR_AXI_BRAM_CTRL_17_WRITE_ACCESS 0U
#define XPAR_AXI_BRAM_CTRL_17_S_AXI_BASEADDR 0xE2000000U
#define XPAR_AXI_BRAM_CTRL_17_S_AXI_HIGHADDR 0xE201FFFFU
#define XPAR_AXI_BRAM_CTRL_17_S_AXI_CTRL_BASEADDR 0xFFFFFFFFU  
#define XPAR_AXI_BRAM_CTRL_17_S_AXI_CTRL_HIGHADDR 0xFFFFFFFFU  


/* Definitions for peripheral AXI_BRAM_CTRL_18 */
#define XPAR_AXI_BRAM_CTRL_18_DEVICE_ID 10U
#define XPAR_AXI_BRAM_CTRL_18_DATA_WIDTH 32U
#define XPAR_AXI_BRAM_CTRL_18_ECC 0U
#define XPAR_AXI_BRAM_CTRL_18_FAULT_INJECT 0U
#define XPAR_AXI_BRAM_CTRL_18_CE_FAILING_REGISTERS 0U
#define XPAR_AXI_BRAM_CTRL_18_UE_FAILING_REGISTERS 0U
#define XPAR_AXI_BRAM_CTRL_18_ECC_STATUS_REGISTERS 0U
#define XPAR_AXI_BRAM_CTRL_18_CE_COUNTER_WIDTH 0U
#define XPAR_AXI_BRAM_CTRL_18_ECC_ONOFF_REGISTER 0U
#define XPAR_AXI_BRAM_CTRL_18_ECC_ONOFF_RESET_VALUE 0U
#define XPAR_AXI_BRAM_CTRL_18_WRITE_ACCESS 0U
#define XPAR_AXI_BRAM_CTRL_18_S_AXI_BASEADDR 0xE4000000U
#define XPAR_AXI_BRAM_CTRL_18_S_AXI_HIGHADDR 0xE401FFFFU
#define XPAR_AXI_BRAM_CTRL_18_S_AXI_CTRL_BASEADDR 0xFFFFFFFFU  
#define XPAR_AXI_BRAM_CTRL_18_S_AXI_CTRL_HIGHADDR 0xFFFFFFFFU  


/* Definitions for peripheral AXI_BRAM_CTRL_19 */
#define XPAR_AXI_BRAM_CTRL_19_DEVICE_ID 11U
#define XPAR_AXI_BRAM_CTRL_19_DATA_WIDTH 32U
#define XPAR_AXI_BRAM_CTRL_19_ECC 0U
#define XPAR_AXI_BRAM_CTRL_19_FAULT_INJECT 0U
#define XPAR_AXI_BRAM_CTRL_19_CE_FAILING_REGISTERS 0U
#define XPAR_AXI_BRAM_CTRL_19_UE_FAILING_REGISTERS 0U
#define XPAR_AXI_BRAM_CTRL_19_ECC_STATUS_REGISTERS 0U
#define XPAR_AXI_BRAM_CTRL_19_CE_COUNTER_WIDTH 0U
#define XPAR_AXI_BRAM_CTRL_19_ECC_ONOFF_REGISTER 0U
#define XPAR_AXI_BRAM_CTRL_19_ECC_ONOFF_RESET_VALUE 0U
#define XPAR_AXI_BRAM_CTRL_19_WRITE_ACCESS 0U
#define XPAR_AXI_BRAM_CTRL_19_S_AXI_BASEADDR 0xE6000000U
#define XPAR_AXI_BRAM_CTRL_19_S_AXI_HIGHADDR 0xE601FFFFU
#define XPAR_AXI_BRAM_CTRL_19_S_AXI_CTRL_BASEADDR 0xFFFFFFFFU  
#define XPAR_AXI_BRAM_CTRL_19_S_AXI_CTRL_HIGHADDR 0xFFFFFFFFU  


/* Definitions for peripheral AXI_BRAM_CTRL_2 */
#define XPAR_AXI_BRAM_CTRL_2_DEVICE_ID 12U
#define XPAR_AXI_BRAM_CTRL_2_DATA_WIDTH 32U
#define XPAR_AXI_BRAM_CTRL_2_ECC 0U
#define XPAR_AXI_BRAM_CTRL_2_FAULT_INJECT 0U
#define XPAR_AXI_BRAM_CTRL_2_CE_FAILING_REGISTERS 0U
#define XPAR_AXI_BRAM_CTRL_2_UE_FAILING_REGISTERS 0U
#define XPAR_AXI_BRAM_CTRL_2_ECC_STATUS_REGISTERS 0U
#define XPAR_AXI_BRAM_CTRL_2_CE_COUNTER_WIDTH 0U
#define XPAR_AXI_BRAM_CTRL_2_ECC_ONOFF_REGISTER 0U
#define XPAR_AXI_BRAM_CTRL_2_ECC_ONOFF_RESET_VALUE 0U
#define XPAR_AXI_BRAM_CTRL_2_WRITE_ACCESS 0U
#define XPAR_AXI_BRAM_CTRL_2_S_AXI_BASEADDR 0xC4000000U
#define XPAR_AXI_BRAM_CTRL_2_S_AXI_HIGHADDR 0xC401FFFFU
#define XPAR_AXI_BRAM_CTRL_2_S_AXI_CTRL_BASEADDR 0xFFFFFFFFU  
#define XPAR_AXI_BRAM_CTRL_2_S_AXI_CTRL_HIGHADDR 0xFFFFFFFFU  


/* Definitions for peripheral AXI_BRAM_CTRL_20 */
#define XPAR_AXI_BRAM_CTRL_20_DEVICE_ID 13U
#define XPAR_AXI_BRAM_CTRL_20_DATA_WIDTH 32U
#define XPAR_AXI_BRAM_CTRL_20_ECC 0U
#define XPAR_AXI_BRAM_CTRL_20_FAULT_INJECT 0U
#define XPAR_AXI_BRAM_CTRL_20_CE_FAILING_REGISTERS 0U
#define XPAR_AXI_BRAM_CTRL_20_UE_FAILING_REGISTERS 0U
#define XPAR_AXI_BRAM_CTRL_20_ECC_STATUS_REGISTERS 0U
#define XPAR_AXI_BRAM_CTRL_20_CE_COUNTER_WIDTH 0U
#define XPAR_AXI_BRAM_CTRL_20_ECC_ONOFF_REGISTER 0U
#define XPAR_AXI_BRAM_CTRL_20_ECC_ONOFF_RESET_VALUE 0U
#define XPAR_AXI_BRAM_CTRL_20_WRITE_ACCESS 0U
#define XPAR_AXI_BRAM_CTRL_20_S_AXI_BASEADDR 0xE8000000U
#define XPAR_AXI_BRAM_CTRL_20_S_AXI_HIGHADDR 0xE801FFFFU
#define XPAR_AXI_BRAM_CTRL_20_S_AXI_CTRL_BASEADDR 0xFFFFFFFFU  
#define XPAR_AXI_BRAM_CTRL_20_S_AXI_CTRL_HIGHADDR 0xFFFFFFFFU  


/* Definitions for peripheral AXI_BRAM_CTRL_21 */
#define XPAR_AXI_BRAM_CTRL_21_DEVICE_ID 14U
#define XPAR_AXI_BRAM_CTRL_21_DATA_WIDTH 32U
#define XPAR_AXI_BRAM_CTRL_21_ECC 0U
#define XPAR_AXI_BRAM_CTRL_21_FAULT_INJECT 0U
#define XPAR_AXI_BRAM_CTRL_21_CE_FAILING_REGISTERS 0U
#define XPAR_AXI_BRAM_CTRL_21_UE_FAILING_REGISTERS 0U
#define XPAR_AXI_BRAM_CTRL_21_ECC_STATUS_REGISTERS 0U
#define XPAR_AXI_BRAM_CTRL_21_CE_COUNTER_WIDTH 0U
#define XPAR_AXI_BRAM_CTRL_21_ECC_ONOFF_REGISTER 0U
#define XPAR_AXI_BRAM_CTRL_21_ECC_ONOFF_RESET_VALUE 0U
#define XPAR_AXI_BRAM_CTRL_21_WRITE_ACCESS 0U
#define XPAR_AXI_BRAM_CTRL_21_S_AXI_BASEADDR 0xEA000000U
#define XPAR_AXI_BRAM_CTRL_21_S_AXI_HIGHADDR 0xEA01FFFFU
#define XPAR_AXI_BRAM_CTRL_21_S_AXI_CTRL_BASEADDR 0xFFFFFFFFU  
#define XPAR_AXI_BRAM_CTRL_21_S_AXI_CTRL_HIGHADDR 0xFFFFFFFFU  


/* Definitions for peripheral AXI_BRAM_CTRL_3 */
#define XPAR_AXI_BRAM_CTRL_3_DEVICE_ID 15U
#define XPAR_AXI_BRAM_CTRL_3_DATA_WIDTH 32U
#define XPAR_AXI_BRAM_CTRL_3_ECC 0U
#define XPAR_AXI_BRAM_CTRL_3_FAULT_INJECT 0U
#define XPAR_AXI_BRAM_CTRL_3_CE_FAILING_REGISTERS 0U
#define XPAR_AXI_BRAM_CTRL_3_UE_FAILING_REGISTERS 0U
#define XPAR_AXI_BRAM_CTRL_3_ECC_STATUS_REGISTERS 0U
#define XPAR_AXI_BRAM_CTRL_3_CE_COUNTER_WIDTH 0U
#define XPAR_AXI_BRAM_CTRL_3_ECC_ONOFF_REGISTER 0U
#define XPAR_AXI_BRAM_CTRL_3_ECC_ONOFF_RESET_VALUE 0U
#define XPAR_AXI_BRAM_CTRL_3_WRITE_ACCESS 0U
#define XPAR_AXI_BRAM_CTRL_3_S_AXI_BASEADDR 0xC6000000U
#define XPAR_AXI_BRAM_CTRL_3_S_AXI_HIGHADDR 0xC601FFFFU
#define XPAR_AXI_BRAM_CTRL_3_S_AXI_CTRL_BASEADDR 0xFFFFFFFFU  
#define XPAR_AXI_BRAM_CTRL_3_S_AXI_CTRL_HIGHADDR 0xFFFFFFFFU  


/* Definitions for peripheral AXI_BRAM_CTRL_4 */
#define XPAR_AXI_BRAM_CTRL_4_DEVICE_ID 16U
#define XPAR_AXI_BRAM_CTRL_4_DATA_WIDTH 32U
#define XPAR_AXI_BRAM_CTRL_4_ECC 0U
#define XPAR_AXI_BRAM_CTRL_4_FAULT_INJECT 0U
#define XPAR_AXI_BRAM_CTRL_4_CE_FAILING_REGISTERS 0U
#define XPAR_AXI_BRAM_CTRL_4_UE_FAILING_REGISTERS 0U
#define XPAR_AXI_BRAM_CTRL_4_ECC_STATUS_REGISTERS 0U
#define XPAR_AXI_BRAM_CTRL_4_CE_COUNTER_WIDTH 0U
#define XPAR_AXI_BRAM_CTRL_4_ECC_ONOFF_REGISTER 0U
#define XPAR_AXI_BRAM_CTRL_4_ECC_ONOFF_RESET_VALUE 0U
#define XPAR_AXI_BRAM_CTRL_4_WRITE_ACCESS 0U
#define XPAR_AXI_BRAM_CTRL_4_S_AXI_BASEADDR 0xC8000000U
#define XPAR_AXI_BRAM_CTRL_4_S_AXI_HIGHADDR 0xC801FFFFU
#define XPAR_AXI_BRAM_CTRL_4_S_AXI_CTRL_BASEADDR 0xFFFFFFFFU  
#define XPAR_AXI_BRAM_CTRL_4_S_AXI_CTRL_HIGHADDR 0xFFFFFFFFU  


/* Definitions for peripheral AXI_BRAM_CTRL_5 */
#define XPAR_AXI_BRAM_CTRL_5_DEVICE_ID 17U
#define XPAR_AXI_BRAM_CTRL_5_DATA_WIDTH 32U
#define XPAR_AXI_BRAM_CTRL_5_ECC 0U
#define XPAR_AXI_BRAM_CTRL_5_FAULT_INJECT 0U
#define XPAR_AXI_BRAM_CTRL_5_CE_FAILING_REGISTERS 0U
#define XPAR_AXI_BRAM_CTRL_5_UE_FAILING_REGISTERS 0U
#define XPAR_AXI_BRAM_CTRL_5_ECC_STATUS_REGISTERS 0U
#define XPAR_AXI_BRAM_CTRL_5_CE_COUNTER_WIDTH 0U
#define XPAR_AXI_BRAM_CTRL_5_ECC_ONOFF_REGISTER 0U
#define XPAR_AXI_BRAM_CTRL_5_ECC_ONOFF_RESET_VALUE 0U
#define XPAR_AXI_BRAM_CTRL_5_WRITE_ACCESS 0U
#define XPAR_AXI_BRAM_CTRL_5_S_AXI_BASEADDR 0xCA000000U
#define XPAR_AXI_BRAM_CTRL_5_S_AXI_HIGHADDR 0xCA01FFFFU
#define XPAR_AXI_BRAM_CTRL_5_S_AXI_CTRL_BASEADDR 0xFFFFFFFFU  
#define XPAR_AXI_BRAM_CTRL_5_S_AXI_CTRL_HIGHADDR 0xFFFFFFFFU  


/* Definitions for peripheral AXI_BRAM_CTRL_6 */
#define XPAR_AXI_BRAM_CTRL_6_DEVICE_ID 18U
#define XPAR_AXI_BRAM_CTRL_6_DATA_WIDTH 32U
#define XPAR_AXI_BRAM_CTRL_6_ECC 0U
#define XPAR_AXI_BRAM_CTRL_6_FAULT_INJECT 0U
#define XPAR_AXI_BRAM_CTRL_6_CE_FAILING_REGISTERS 0U
#define XPAR_AXI_BRAM_CTRL_6_UE_FAILING_REGISTERS 0U
#define XPAR_AXI_BRAM_CTRL_6_ECC_STATUS_REGISTERS 0U
#define XPAR_AXI_BRAM_CTRL_6_CE_COUNTER_WIDTH 0U
#define XPAR_AXI_BRAM_CTRL_6_ECC_ONOFF_REGISTER 0U
#define XPAR_AXI_BRAM_CTRL_6_ECC_ONOFF_RESET_VALUE 0U
#define XPAR_AXI_BRAM_CTRL_6_WRITE_ACCESS 0U
#define XPAR_AXI_BRAM_CTRL_6_S_AXI_BASEADDR 0xCC000000U
#define XPAR_AXI_BRAM_CTRL_6_S_AXI_HIGHADDR 0xCC01FFFFU
#define XPAR_AXI_BRAM_CTRL_6_S_AXI_CTRL_BASEADDR 0xFFFFFFFFU  
#define XPAR_AXI_BRAM_CTRL_6_S_AXI_CTRL_HIGHADDR 0xFFFFFFFFU  


/* Definitions for peripheral AXI_BRAM_CTRL_7 */
#define XPAR_AXI_BRAM_CTRL_7_DEVICE_ID 19U
#define XPAR_AXI_BRAM_CTRL_7_DATA_WIDTH 32U
#define XPAR_AXI_BRAM_CTRL_7_ECC 0U
#define XPAR_AXI_BRAM_CTRL_7_FAULT_INJECT 0U
#define XPAR_AXI_BRAM_CTRL_7_CE_FAILING_REGISTERS 0U
#define XPAR_AXI_BRAM_CTRL_7_UE_FAILING_REGISTERS 0U
#define XPAR_AXI_BRAM_CTRL_7_ECC_STATUS_REGISTERS 0U
#define XPAR_AXI_BRAM_CTRL_7_CE_COUNTER_WIDTH 0U
#define XPAR_AXI_BRAM_CTRL_7_ECC_ONOFF_REGISTER 0U
#define XPAR_AXI_BRAM_CTRL_7_ECC_ONOFF_RESET_VALUE 0U
#define XPAR_AXI_BRAM_CTRL_7_WRITE_ACCESS 0U
#define XPAR_AXI_BRAM_CTRL_7_S_AXI_BASEADDR 0xCE000000U
#define XPAR_AXI_BRAM_CTRL_7_S_AXI_HIGHADDR 0xCE01FFFFU
#define XPAR_AXI_BRAM_CTRL_7_S_AXI_CTRL_BASEADDR 0xFFFFFFFFU  
#define XPAR_AXI_BRAM_CTRL_7_S_AXI_CTRL_HIGHADDR 0xFFFFFFFFU  


/* Definitions for peripheral AXI_BRAM_CTRL_8 */
#define XPAR_AXI_BRAM_CTRL_8_DEVICE_ID 20U
#define XPAR_AXI_BRAM_CTRL_8_DATA_WIDTH 32U
#define XPAR_AXI_BRAM_CTRL_8_ECC 0U
#define XPAR_AXI_BRAM_CTRL_8_FAULT_INJECT 0U
#define XPAR_AXI_BRAM_CTRL_8_CE_FAILING_REGISTERS 0U
#define XPAR_AXI_BRAM_CTRL_8_UE_FAILING_REGISTERS 0U
#define XPAR_AXI_BRAM_CTRL_8_ECC_STATUS_REGISTERS 0U
#define XPAR_AXI_BRAM_CTRL_8_CE_COUNTER_WIDTH 0U
#define XPAR_AXI_BRAM_CTRL_8_ECC_ONOFF_REGISTER 0U
#define XPAR_AXI_BRAM_CTRL_8_ECC_ONOFF_RESET_VALUE 0U
#define XPAR_AXI_BRAM_CTRL_8_WRITE_ACCESS 0U
#define XPAR_AXI_BRAM_CTRL_8_S_AXI_BASEADDR 0xD0000000U
#define XPAR_AXI_BRAM_CTRL_8_S_AXI_HIGHADDR 0xD001FFFFU
#define XPAR_AXI_BRAM_CTRL_8_S_AXI_CTRL_BASEADDR 0xFFFFFFFFU  
#define XPAR_AXI_BRAM_CTRL_8_S_AXI_CTRL_HIGHADDR 0xFFFFFFFFU  


/* Definitions for peripheral AXI_BRAM_CTRL_9 */
#define XPAR_AXI_BRAM_CTRL_9_DEVICE_ID 21U
#define XPAR_AXI_BRAM_CTRL_9_DATA_WIDTH 32U
#define XPAR_AXI_BRAM_CTRL_9_ECC 0U
#define XPAR_AXI_BRAM_CTRL_9_FAULT_INJECT 0U
#define XPAR_AXI_BRAM_CTRL_9_CE_FAILING_REGISTERS 0U
#define XPAR_AXI_BRAM_CTRL_9_UE_FAILING_REGISTERS 0U
#define XPAR_AXI_BRAM_CTRL_9_ECC_STATUS_REGISTERS 0U
#define XPAR_AXI_BRAM_CTRL_9_CE_COUNTER_WIDTH 0U
#define XPAR_AXI_BRAM_CTRL_9_ECC_ONOFF_REGISTER 0U
#define XPAR_AXI_BRAM_CTRL_9_ECC_ONOFF_RESET_VALUE 0U
#define XPAR_AXI_BRAM_CTRL_9_WRITE_ACCESS 0U
#define XPAR_AXI_BRAM_CTRL_9_S_AXI_BASEADDR 0xD2000000U
#define XPAR_AXI_BRAM_CTRL_9_S_AXI_HIGHADDR 0xD201FFFFU
#define XPAR_AXI_BRAM_CTRL_9_S_AXI_CTRL_BASEADDR 0xFFFFFFFFU  
#define XPAR_AXI_BRAM_CTRL_9_S_AXI_CTRL_HIGHADDR 0xFFFFFFFFU  


/* Definitions for peripheral MICROBLAZE_0_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR */
#define XPAR_MICROBLAZE_0_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_DEVICE_ID 22U
#define XPAR_MICROBLAZE_0_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_DATA_WIDTH 32U
#define XPAR_MICROBLAZE_0_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_ECC 0U
#define XPAR_MICROBLAZE_0_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_FAULT_INJECT 0U
#define XPAR_MICROBLAZE_0_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_CE_FAILING_REGISTERS 0U
#define XPAR_MICROBLAZE_0_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_UE_FAILING_REGISTERS 0U
#define XPAR_MICROBLAZE_0_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_ECC_STATUS_REGISTERS 0U
#define XPAR_MICROBLAZE_0_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_CE_COUNTER_WIDTH 0U
#define XPAR_MICROBLAZE_0_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_ECC_ONOFF_REGISTER 0U
#define XPAR_MICROBLAZE_0_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_ECC_ONOFF_RESET_VALUE 1U
#define XPAR_MICROBLAZE_0_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_WRITE_ACCESS 2U
#define XPAR_MICROBLAZE_0_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_BASEADDR 0x00000000U
#define XPAR_MICROBLAZE_0_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_HIGHADDR 0x000FFFFFU
#define XPAR_MICROBLAZE_0_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_S_AXI_CTRL_BASEADDR 0xFFFFFFFFU  
#define XPAR_MICROBLAZE_0_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_S_AXI_CTRL_HIGHADDR 0xFFFFFFFFU  


/* Definitions for peripheral MICROBLAZE_0_LOCAL_MEMORY_ILMB_BRAM_IF_CNTLR */
#define XPAR_MICROBLAZE_0_LOCAL_MEMORY_ILMB_BRAM_IF_CNTLR_DEVICE_ID 23U
#define XPAR_MICROBLAZE_0_LOCAL_MEMORY_ILMB_BRAM_IF_CNTLR_DATA_WIDTH 32U
#define XPAR_MICROBLAZE_0_LOCAL_MEMORY_ILMB_BRAM_IF_CNTLR_ECC 0U
#define XPAR_MICROBLAZE_0_LOCAL_MEMORY_ILMB_BRAM_IF_CNTLR_FAULT_INJECT 0U
#define XPAR_MICROBLAZE_0_LOCAL_MEMORY_ILMB_BRAM_IF_CNTLR_CE_FAILING_REGISTERS 0U
#define XPAR_MICROBLAZE_0_LOCAL_MEMORY_ILMB_BRAM_IF_CNTLR_UE_FAILING_REGISTERS 0U
#define XPAR_MICROBLAZE_0_LOCAL_MEMORY_ILMB_BRAM_IF_CNTLR_ECC_STATUS_REGISTERS 0U
#define XPAR_MICROBLAZE_0_LOCAL_MEMORY_ILMB_BRAM_IF_CNTLR_CE_COUNTER_WIDTH 0U
#define XPAR_MICROBLAZE_0_LOCAL_MEMORY_ILMB_BRAM_IF_CNTLR_ECC_ONOFF_REGISTER 0U
#define XPAR_MICROBLAZE_0_LOCAL_MEMORY_ILMB_BRAM_IF_CNTLR_ECC_ONOFF_RESET_VALUE 1U
#define XPAR_MICROBLAZE_0_LOCAL_MEMORY_ILMB_BRAM_IF_CNTLR_WRITE_ACCESS 2U
#define XPAR_MICROBLAZE_0_LOCAL_MEMORY_ILMB_BRAM_IF_CNTLR_BASEADDR 0x00000000U
#define XPAR_MICROBLAZE_0_LOCAL_MEMORY_ILMB_BRAM_IF_CNTLR_HIGHADDR 0x000FFFFFU
#define XPAR_MICROBLAZE_0_LOCAL_MEMORY_ILMB_BRAM_IF_CNTLR_S_AXI_CTRL_BASEADDR 0xFFFFFFFFU  
#define XPAR_MICROBLAZE_0_LOCAL_MEMORY_ILMB_BRAM_IF_CNTLR_S_AXI_CTRL_HIGHADDR 0xFFFFFFFFU  


/******************************************************************/

/* Canonical definitions for peripheral AXI_BRAM_CTRL_0 */
#define XPAR_BRAM_0_DEVICE_ID XPAR_AXI_BRAM_CTRL_0_DEVICE_ID
#define XPAR_BRAM_0_DATA_WIDTH 32U
#define XPAR_BRAM_0_ECC 0U
#define XPAR_BRAM_0_FAULT_INJECT 0U
#define XPAR_BRAM_0_CE_FAILING_REGISTERS 0U
#define XPAR_BRAM_0_UE_FAILING_REGISTERS 0U
#define XPAR_BRAM_0_ECC_STATUS_REGISTERS 0U
#define XPAR_BRAM_0_CE_COUNTER_WIDTH 0U
#define XPAR_BRAM_0_ECC_ONOFF_REGISTER 0U
#define XPAR_BRAM_0_ECC_ONOFF_RESET_VALUE 0U
#define XPAR_BRAM_0_WRITE_ACCESS 0U
#define XPAR_BRAM_0_BASEADDR 0xC0000000U
#define XPAR_BRAM_0_HIGHADDR 0xC001FFFFU
#define XPAR_BRAM_0_CTRL_BASEADDR 0xFFFFFFFFU  
#define XPAR_BRAM_0_CTRL_HIGHADDR 0xFFFFFFFEU  

/* Canonical definitions for peripheral AXI_BRAM_CTRL_1 */
#define XPAR_BRAM_1_DEVICE_ID XPAR_AXI_BRAM_CTRL_1_DEVICE_ID
#define XPAR_BRAM_1_DATA_WIDTH 32U
#define XPAR_BRAM_1_ECC 0U
#define XPAR_BRAM_1_FAULT_INJECT 0U
#define XPAR_BRAM_1_CE_FAILING_REGISTERS 0U
#define XPAR_BRAM_1_UE_FAILING_REGISTERS 0U
#define XPAR_BRAM_1_ECC_STATUS_REGISTERS 0U
#define XPAR_BRAM_1_CE_COUNTER_WIDTH 0U
#define XPAR_BRAM_1_ECC_ONOFF_REGISTER 0U
#define XPAR_BRAM_1_ECC_ONOFF_RESET_VALUE 0U
#define XPAR_BRAM_1_WRITE_ACCESS 0U
#define XPAR_BRAM_1_BASEADDR 0xC2000000U
#define XPAR_BRAM_1_HIGHADDR 0xC201FFFFU
#define XPAR_BRAM_1_CTRL_BASEADDR 0xFFFFFFFFU  
#define XPAR_BRAM_1_CTRL_HIGHADDR 0xFFFFFFFEU  

/* Canonical definitions for peripheral AXI_BRAM_CTRL_10 */
#define XPAR_BRAM_2_DEVICE_ID XPAR_AXI_BRAM_CTRL_10_DEVICE_ID
#define XPAR_BRAM_2_DATA_WIDTH 32U
#define XPAR_BRAM_2_ECC 0U
#define XPAR_BRAM_2_FAULT_INJECT 0U
#define XPAR_BRAM_2_CE_FAILING_REGISTERS 0U
#define XPAR_BRAM_2_UE_FAILING_REGISTERS 0U
#define XPAR_BRAM_2_ECC_STATUS_REGISTERS 0U
#define XPAR_BRAM_2_CE_COUNTER_WIDTH 0U
#define XPAR_BRAM_2_ECC_ONOFF_REGISTER 0U
#define XPAR_BRAM_2_ECC_ONOFF_RESET_VALUE 0U
#define XPAR_BRAM_2_WRITE_ACCESS 0U
#define XPAR_BRAM_2_BASEADDR 0xD4000000U
#define XPAR_BRAM_2_HIGHADDR 0xD401FFFFU
#define XPAR_BRAM_2_CTRL_BASEADDR 0xFFFFFFFFU  
#define XPAR_BRAM_2_CTRL_HIGHADDR 0xFFFFFFFEU  

/* Canonical definitions for peripheral AXI_BRAM_CTRL_11 */
#define XPAR_BRAM_3_DEVICE_ID XPAR_AXI_BRAM_CTRL_11_DEVICE_ID
#define XPAR_BRAM_3_DATA_WIDTH 32U
#define XPAR_BRAM_3_ECC 0U
#define XPAR_BRAM_3_FAULT_INJECT 0U
#define XPAR_BRAM_3_CE_FAILING_REGISTERS 0U
#define XPAR_BRAM_3_UE_FAILING_REGISTERS 0U
#define XPAR_BRAM_3_ECC_STATUS_REGISTERS 0U
#define XPAR_BRAM_3_CE_COUNTER_WIDTH 0U
#define XPAR_BRAM_3_ECC_ONOFF_REGISTER 0U
#define XPAR_BRAM_3_ECC_ONOFF_RESET_VALUE 0U
#define XPAR_BRAM_3_WRITE_ACCESS 0U
#define XPAR_BRAM_3_BASEADDR 0xD6000000U
#define XPAR_BRAM_3_HIGHADDR 0xD601FFFFU
#define XPAR_BRAM_3_CTRL_BASEADDR 0xFFFFFFFFU  
#define XPAR_BRAM_3_CTRL_HIGHADDR 0xFFFFFFFEU  

/* Canonical definitions for peripheral AXI_BRAM_CTRL_12 */
#define XPAR_BRAM_4_DEVICE_ID XPAR_AXI_BRAM_CTRL_12_DEVICE_ID
#define XPAR_BRAM_4_DATA_WIDTH 32U
#define XPAR_BRAM_4_ECC 0U
#define XPAR_BRAM_4_FAULT_INJECT 0U
#define XPAR_BRAM_4_CE_FAILING_REGISTERS 0U
#define XPAR_BRAM_4_UE_FAILING_REGISTERS 0U
#define XPAR_BRAM_4_ECC_STATUS_REGISTERS 0U
#define XPAR_BRAM_4_CE_COUNTER_WIDTH 0U
#define XPAR_BRAM_4_ECC_ONOFF_REGISTER 0U
#define XPAR_BRAM_4_ECC_ONOFF_RESET_VALUE 0U
#define XPAR_BRAM_4_WRITE_ACCESS 0U
#define XPAR_BRAM_4_BASEADDR 0xD8000000U
#define XPAR_BRAM_4_HIGHADDR 0xD801FFFFU
#define XPAR_BRAM_4_CTRL_BASEADDR 0xFFFFFFFFU  
#define XPAR_BRAM_4_CTRL_HIGHADDR 0xFFFFFFFEU  

/* Canonical definitions for peripheral AXI_BRAM_CTRL_13 */
#define XPAR_BRAM_5_DEVICE_ID XPAR_AXI_BRAM_CTRL_13_DEVICE_ID
#define XPAR_BRAM_5_DATA_WIDTH 32U
#define XPAR_BRAM_5_ECC 0U
#define XPAR_BRAM_5_FAULT_INJECT 0U
#define XPAR_BRAM_5_CE_FAILING_REGISTERS 0U
#define XPAR_BRAM_5_UE_FAILING_REGISTERS 0U
#define XPAR_BRAM_5_ECC_STATUS_REGISTERS 0U
#define XPAR_BRAM_5_CE_COUNTER_WIDTH 0U
#define XPAR_BRAM_5_ECC_ONOFF_REGISTER 0U
#define XPAR_BRAM_5_ECC_ONOFF_RESET_VALUE 0U
#define XPAR_BRAM_5_WRITE_ACCESS 0U
#define XPAR_BRAM_5_BASEADDR 0xDA000000U
#define XPAR_BRAM_5_HIGHADDR 0xDA01FFFFU
#define XPAR_BRAM_5_CTRL_BASEADDR 0xFFFFFFFFU  
#define XPAR_BRAM_5_CTRL_HIGHADDR 0xFFFFFFFEU  

/* Canonical definitions for peripheral AXI_BRAM_CTRL_14 */
#define XPAR_BRAM_6_DEVICE_ID XPAR_AXI_BRAM_CTRL_14_DEVICE_ID
#define XPAR_BRAM_6_DATA_WIDTH 32U
#define XPAR_BRAM_6_ECC 0U
#define XPAR_BRAM_6_FAULT_INJECT 0U
#define XPAR_BRAM_6_CE_FAILING_REGISTERS 0U
#define XPAR_BRAM_6_UE_FAILING_REGISTERS 0U
#define XPAR_BRAM_6_ECC_STATUS_REGISTERS 0U
#define XPAR_BRAM_6_CE_COUNTER_WIDTH 0U
#define XPAR_BRAM_6_ECC_ONOFF_REGISTER 0U
#define XPAR_BRAM_6_ECC_ONOFF_RESET_VALUE 0U
#define XPAR_BRAM_6_WRITE_ACCESS 0U
#define XPAR_BRAM_6_BASEADDR 0xDC000000U
#define XPAR_BRAM_6_HIGHADDR 0xDC01FFFFU
#define XPAR_BRAM_6_CTRL_BASEADDR 0xFFFFFFFFU  
#define XPAR_BRAM_6_CTRL_HIGHADDR 0xFFFFFFFEU  

/* Canonical definitions for peripheral AXI_BRAM_CTRL_15 */
#define XPAR_BRAM_7_DEVICE_ID XPAR_AXI_BRAM_CTRL_15_DEVICE_ID
#define XPAR_BRAM_7_DATA_WIDTH 32U
#define XPAR_BRAM_7_ECC 0U
#define XPAR_BRAM_7_FAULT_INJECT 0U
#define XPAR_BRAM_7_CE_FAILING_REGISTERS 0U
#define XPAR_BRAM_7_UE_FAILING_REGISTERS 0U
#define XPAR_BRAM_7_ECC_STATUS_REGISTERS 0U
#define XPAR_BRAM_7_CE_COUNTER_WIDTH 0U
#define XPAR_BRAM_7_ECC_ONOFF_REGISTER 0U
#define XPAR_BRAM_7_ECC_ONOFF_RESET_VALUE 0U
#define XPAR_BRAM_7_WRITE_ACCESS 0U
#define XPAR_BRAM_7_BASEADDR 0xDE000000U
#define XPAR_BRAM_7_HIGHADDR 0xDE01FFFFU
#define XPAR_BRAM_7_CTRL_BASEADDR 0xFFFFFFFFU  
#define XPAR_BRAM_7_CTRL_HIGHADDR 0xFFFFFFFEU  

/* Canonical definitions for peripheral AXI_BRAM_CTRL_16 */
#define XPAR_BRAM_8_DEVICE_ID XPAR_AXI_BRAM_CTRL_16_DEVICE_ID
#define XPAR_BRAM_8_DATA_WIDTH 32U
#define XPAR_BRAM_8_ECC 0U
#define XPAR_BRAM_8_FAULT_INJECT 0U
#define XPAR_BRAM_8_CE_FAILING_REGISTERS 0U
#define XPAR_BRAM_8_UE_FAILING_REGISTERS 0U
#define XPAR_BRAM_8_ECC_STATUS_REGISTERS 0U
#define XPAR_BRAM_8_CE_COUNTER_WIDTH 0U
#define XPAR_BRAM_8_ECC_ONOFF_REGISTER 0U
#define XPAR_BRAM_8_ECC_ONOFF_RESET_VALUE 0U
#define XPAR_BRAM_8_WRITE_ACCESS 0U
#define XPAR_BRAM_8_BASEADDR 0xE0000000U
#define XPAR_BRAM_8_HIGHADDR 0xE001FFFFU
#define XPAR_BRAM_8_CTRL_BASEADDR 0xFFFFFFFFU  
#define XPAR_BRAM_8_CTRL_HIGHADDR 0xFFFFFFFEU  

/* Canonical definitions for peripheral AXI_BRAM_CTRL_17 */
#define XPAR_BRAM_9_DEVICE_ID XPAR_AXI_BRAM_CTRL_17_DEVICE_ID
#define XPAR_BRAM_9_DATA_WIDTH 32U
#define XPAR_BRAM_9_ECC 0U
#define XPAR_BRAM_9_FAULT_INJECT 0U
#define XPAR_BRAM_9_CE_FAILING_REGISTERS 0U
#define XPAR_BRAM_9_UE_FAILING_REGISTERS 0U
#define XPAR_BRAM_9_ECC_STATUS_REGISTERS 0U
#define XPAR_BRAM_9_CE_COUNTER_WIDTH 0U
#define XPAR_BRAM_9_ECC_ONOFF_REGISTER 0U
#define XPAR_BRAM_9_ECC_ONOFF_RESET_VALUE 0U
#define XPAR_BRAM_9_WRITE_ACCESS 0U
#define XPAR_BRAM_9_BASEADDR 0xE2000000U
#define XPAR_BRAM_9_HIGHADDR 0xE201FFFFU
#define XPAR_BRAM_9_CTRL_BASEADDR 0xFFFFFFFFU  
#define XPAR_BRAM_9_CTRL_HIGHADDR 0xFFFFFFFEU  

/* Canonical definitions for peripheral AXI_BRAM_CTRL_18 */
#define XPAR_BRAM_10_DEVICE_ID XPAR_AXI_BRAM_CTRL_18_DEVICE_ID
#define XPAR_BRAM_10_DATA_WIDTH 32U
#define XPAR_BRAM_10_ECC 0U
#define XPAR_BRAM_10_FAULT_INJECT 0U
#define XPAR_BRAM_10_CE_FAILING_REGISTERS 0U
#define XPAR_BRAM_10_UE_FAILING_REGISTERS 0U
#define XPAR_BRAM_10_ECC_STATUS_REGISTERS 0U
#define XPAR_BRAM_10_CE_COUNTER_WIDTH 0U
#define XPAR_BRAM_10_ECC_ONOFF_REGISTER 0U
#define XPAR_BRAM_10_ECC_ONOFF_RESET_VALUE 0U
#define XPAR_BRAM_10_WRITE_ACCESS 0U
#define XPAR_BRAM_10_BASEADDR 0xE4000000U
#define XPAR_BRAM_10_HIGHADDR 0xE401FFFFU
#define XPAR_BRAM_10_CTRL_BASEADDR 0xFFFFFFFFU  
#define XPAR_BRAM_10_CTRL_HIGHADDR 0xFFFFFFFEU  

/* Canonical definitions for peripheral AXI_BRAM_CTRL_19 */
#define XPAR_BRAM_11_DEVICE_ID XPAR_AXI_BRAM_CTRL_19_DEVICE_ID
#define XPAR_BRAM_11_DATA_WIDTH 32U
#define XPAR_BRAM_11_ECC 0U
#define XPAR_BRAM_11_FAULT_INJECT 0U
#define XPAR_BRAM_11_CE_FAILING_REGISTERS 0U
#define XPAR_BRAM_11_UE_FAILING_REGISTERS 0U
#define XPAR_BRAM_11_ECC_STATUS_REGISTERS 0U
#define XPAR_BRAM_11_CE_COUNTER_WIDTH 0U
#define XPAR_BRAM_11_ECC_ONOFF_REGISTER 0U
#define XPAR_BRAM_11_ECC_ONOFF_RESET_VALUE 0U
#define XPAR_BRAM_11_WRITE_ACCESS 0U
#define XPAR_BRAM_11_BASEADDR 0xE6000000U
#define XPAR_BRAM_11_HIGHADDR 0xE601FFFFU
#define XPAR_BRAM_11_CTRL_BASEADDR 0xFFFFFFFFU  
#define XPAR_BRAM_11_CTRL_HIGHADDR 0xFFFFFFFEU  

/* Canonical definitions for peripheral AXI_BRAM_CTRL_2 */
#define XPAR_BRAM_12_DEVICE_ID XPAR_AXI_BRAM_CTRL_2_DEVICE_ID
#define XPAR_BRAM_12_DATA_WIDTH 32U
#define XPAR_BRAM_12_ECC 0U
#define XPAR_BRAM_12_FAULT_INJECT 0U
#define XPAR_BRAM_12_CE_FAILING_REGISTERS 0U
#define XPAR_BRAM_12_UE_FAILING_REGISTERS 0U
#define XPAR_BRAM_12_ECC_STATUS_REGISTERS 0U
#define XPAR_BRAM_12_CE_COUNTER_WIDTH 0U
#define XPAR_BRAM_12_ECC_ONOFF_REGISTER 0U
#define XPAR_BRAM_12_ECC_ONOFF_RESET_VALUE 0U
#define XPAR_BRAM_12_WRITE_ACCESS 0U
#define XPAR_BRAM_12_BASEADDR 0xC4000000U
#define XPAR_BRAM_12_HIGHADDR 0xC401FFFFU
#define XPAR_BRAM_12_CTRL_BASEADDR 0xFFFFFFFFU  
#define XPAR_BRAM_12_CTRL_HIGHADDR 0xFFFFFFFEU  

/* Canonical definitions for peripheral AXI_BRAM_CTRL_20 */
#define XPAR_BRAM_13_DEVICE_ID XPAR_AXI_BRAM_CTRL_20_DEVICE_ID
#define XPAR_BRAM_13_DATA_WIDTH 32U
#define XPAR_BRAM_13_ECC 0U
#define XPAR_BRAM_13_FAULT_INJECT 0U
#define XPAR_BRAM_13_CE_FAILING_REGISTERS 0U
#define XPAR_BRAM_13_UE_FAILING_REGISTERS 0U
#define XPAR_BRAM_13_ECC_STATUS_REGISTERS 0U
#define XPAR_BRAM_13_CE_COUNTER_WIDTH 0U
#define XPAR_BRAM_13_ECC_ONOFF_REGISTER 0U
#define XPAR_BRAM_13_ECC_ONOFF_RESET_VALUE 0U
#define XPAR_BRAM_13_WRITE_ACCESS 0U
#define XPAR_BRAM_13_BASEADDR 0xE8000000U
#define XPAR_BRAM_13_HIGHADDR 0xE801FFFFU
#define XPAR_BRAM_13_CTRL_BASEADDR 0xFFFFFFFFU  
#define XPAR_BRAM_13_CTRL_HIGHADDR 0xFFFFFFFEU  

/* Canonical definitions for peripheral AXI_BRAM_CTRL_21 */
#define XPAR_BRAM_14_DEVICE_ID XPAR_AXI_BRAM_CTRL_21_DEVICE_ID
#define XPAR_BRAM_14_DATA_WIDTH 32U
#define XPAR_BRAM_14_ECC 0U
#define XPAR_BRAM_14_FAULT_INJECT 0U
#define XPAR_BRAM_14_CE_FAILING_REGISTERS 0U
#define XPAR_BRAM_14_UE_FAILING_REGISTERS 0U
#define XPAR_BRAM_14_ECC_STATUS_REGISTERS 0U
#define XPAR_BRAM_14_CE_COUNTER_WIDTH 0U
#define XPAR_BRAM_14_ECC_ONOFF_REGISTER 0U
#define XPAR_BRAM_14_ECC_ONOFF_RESET_VALUE 0U
#define XPAR_BRAM_14_WRITE_ACCESS 0U
#define XPAR_BRAM_14_BASEADDR 0xEA000000U
#define XPAR_BRAM_14_HIGHADDR 0xEA01FFFFU
#define XPAR_BRAM_14_CTRL_BASEADDR 0xFFFFFFFFU  
#define XPAR_BRAM_14_CTRL_HIGHADDR 0xFFFFFFFEU  

/* Canonical definitions for peripheral AXI_BRAM_CTRL_3 */
#define XPAR_BRAM_15_DEVICE_ID XPAR_AXI_BRAM_CTRL_3_DEVICE_ID
#define XPAR_BRAM_15_DATA_WIDTH 32U
#define XPAR_BRAM_15_ECC 0U
#define XPAR_BRAM_15_FAULT_INJECT 0U
#define XPAR_BRAM_15_CE_FAILING_REGISTERS 0U
#define XPAR_BRAM_15_UE_FAILING_REGISTERS 0U
#define XPAR_BRAM_15_ECC_STATUS_REGISTERS 0U
#define XPAR_BRAM_15_CE_COUNTER_WIDTH 0U
#define XPAR_BRAM_15_ECC_ONOFF_REGISTER 0U
#define XPAR_BRAM_15_ECC_ONOFF_RESET_VALUE 0U
#define XPAR_BRAM_15_WRITE_ACCESS 0U
#define XPAR_BRAM_15_BASEADDR 0xC6000000U
#define XPAR_BRAM_15_HIGHADDR 0xC601FFFFU
#define XPAR_BRAM_15_CTRL_BASEADDR 0xFFFFFFFFU  
#define XPAR_BRAM_15_CTRL_HIGHADDR 0xFFFFFFFEU  

/* Canonical definitions for peripheral AXI_BRAM_CTRL_4 */
#define XPAR_BRAM_16_DEVICE_ID XPAR_AXI_BRAM_CTRL_4_DEVICE_ID
#define XPAR_BRAM_16_DATA_WIDTH 32U
#define XPAR_BRAM_16_ECC 0U
#define XPAR_BRAM_16_FAULT_INJECT 0U
#define XPAR_BRAM_16_CE_FAILING_REGISTERS 0U
#define XPAR_BRAM_16_UE_FAILING_REGISTERS 0U
#define XPAR_BRAM_16_ECC_STATUS_REGISTERS 0U
#define XPAR_BRAM_16_CE_COUNTER_WIDTH 0U
#define XPAR_BRAM_16_ECC_ONOFF_REGISTER 0U
#define XPAR_BRAM_16_ECC_ONOFF_RESET_VALUE 0U
#define XPAR_BRAM_16_WRITE_ACCESS 0U
#define XPAR_BRAM_16_BASEADDR 0xC8000000U
#define XPAR_BRAM_16_HIGHADDR 0xC801FFFFU
#define XPAR_BRAM_16_CTRL_BASEADDR 0xFFFFFFFFU  
#define XPAR_BRAM_16_CTRL_HIGHADDR 0xFFFFFFFEU  

/* Canonical definitions for peripheral AXI_BRAM_CTRL_5 */
#define XPAR_BRAM_17_DEVICE_ID XPAR_AXI_BRAM_CTRL_5_DEVICE_ID
#define XPAR_BRAM_17_DATA_WIDTH 32U
#define XPAR_BRAM_17_ECC 0U
#define XPAR_BRAM_17_FAULT_INJECT 0U
#define XPAR_BRAM_17_CE_FAILING_REGISTERS 0U
#define XPAR_BRAM_17_UE_FAILING_REGISTERS 0U
#define XPAR_BRAM_17_ECC_STATUS_REGISTERS 0U
#define XPAR_BRAM_17_CE_COUNTER_WIDTH 0U
#define XPAR_BRAM_17_ECC_ONOFF_REGISTER 0U
#define XPAR_BRAM_17_ECC_ONOFF_RESET_VALUE 0U
#define XPAR_BRAM_17_WRITE_ACCESS 0U
#define XPAR_BRAM_17_BASEADDR 0xCA000000U
#define XPAR_BRAM_17_HIGHADDR 0xCA01FFFFU
#define XPAR_BRAM_17_CTRL_BASEADDR 0xFFFFFFFFU  
#define XPAR_BRAM_17_CTRL_HIGHADDR 0xFFFFFFFEU  

/* Canonical definitions for peripheral AXI_BRAM_CTRL_6 */
#define XPAR_BRAM_18_DEVICE_ID XPAR_AXI_BRAM_CTRL_6_DEVICE_ID
#define XPAR_BRAM_18_DATA_WIDTH 32U
#define XPAR_BRAM_18_ECC 0U
#define XPAR_BRAM_18_FAULT_INJECT 0U
#define XPAR_BRAM_18_CE_FAILING_REGISTERS 0U
#define XPAR_BRAM_18_UE_FAILING_REGISTERS 0U
#define XPAR_BRAM_18_ECC_STATUS_REGISTERS 0U
#define XPAR_BRAM_18_CE_COUNTER_WIDTH 0U
#define XPAR_BRAM_18_ECC_ONOFF_REGISTER 0U
#define XPAR_BRAM_18_ECC_ONOFF_RESET_VALUE 0U
#define XPAR_BRAM_18_WRITE_ACCESS 0U
#define XPAR_BRAM_18_BASEADDR 0xCC000000U
#define XPAR_BRAM_18_HIGHADDR 0xCC01FFFFU
#define XPAR_BRAM_18_CTRL_BASEADDR 0xFFFFFFFFU  
#define XPAR_BRAM_18_CTRL_HIGHADDR 0xFFFFFFFEU  

/* Canonical definitions for peripheral AXI_BRAM_CTRL_7 */
#define XPAR_BRAM_19_DEVICE_ID XPAR_AXI_BRAM_CTRL_7_DEVICE_ID
#define XPAR_BRAM_19_DATA_WIDTH 32U
#define XPAR_BRAM_19_ECC 0U
#define XPAR_BRAM_19_FAULT_INJECT 0U
#define XPAR_BRAM_19_CE_FAILING_REGISTERS 0U
#define XPAR_BRAM_19_UE_FAILING_REGISTERS 0U
#define XPAR_BRAM_19_ECC_STATUS_REGISTERS 0U
#define XPAR_BRAM_19_CE_COUNTER_WIDTH 0U
#define XPAR_BRAM_19_ECC_ONOFF_REGISTER 0U
#define XPAR_BRAM_19_ECC_ONOFF_RESET_VALUE 0U
#define XPAR_BRAM_19_WRITE_ACCESS 0U
#define XPAR_BRAM_19_BASEADDR 0xCE000000U
#define XPAR_BRAM_19_HIGHADDR 0xCE01FFFFU
#define XPAR_BRAM_19_CTRL_BASEADDR 0xFFFFFFFFU  
#define XPAR_BRAM_19_CTRL_HIGHADDR 0xFFFFFFFEU  

/* Canonical definitions for peripheral AXI_BRAM_CTRL_8 */
#define XPAR_BRAM_20_DEVICE_ID XPAR_AXI_BRAM_CTRL_8_DEVICE_ID
#define XPAR_BRAM_20_DATA_WIDTH 32U
#define XPAR_BRAM_20_ECC 0U
#define XPAR_BRAM_20_FAULT_INJECT 0U
#define XPAR_BRAM_20_CE_FAILING_REGISTERS 0U
#define XPAR_BRAM_20_UE_FAILING_REGISTERS 0U
#define XPAR_BRAM_20_ECC_STATUS_REGISTERS 0U
#define XPAR_BRAM_20_CE_COUNTER_WIDTH 0U
#define XPAR_BRAM_20_ECC_ONOFF_REGISTER 0U
#define XPAR_BRAM_20_ECC_ONOFF_RESET_VALUE 0U
#define XPAR_BRAM_20_WRITE_ACCESS 0U
#define XPAR_BRAM_20_BASEADDR 0xD0000000U
#define XPAR_BRAM_20_HIGHADDR 0xD001FFFFU
#define XPAR_BRAM_20_CTRL_BASEADDR 0xFFFFFFFFU  
#define XPAR_BRAM_20_CTRL_HIGHADDR 0xFFFFFFFEU  

/* Canonical definitions for peripheral AXI_BRAM_CTRL_9 */
#define XPAR_BRAM_21_DEVICE_ID XPAR_AXI_BRAM_CTRL_9_DEVICE_ID
#define XPAR_BRAM_21_DATA_WIDTH 32U
#define XPAR_BRAM_21_ECC 0U
#define XPAR_BRAM_21_FAULT_INJECT 0U
#define XPAR_BRAM_21_CE_FAILING_REGISTERS 0U
#define XPAR_BRAM_21_UE_FAILING_REGISTERS 0U
#define XPAR_BRAM_21_ECC_STATUS_REGISTERS 0U
#define XPAR_BRAM_21_CE_COUNTER_WIDTH 0U
#define XPAR_BRAM_21_ECC_ONOFF_REGISTER 0U
#define XPAR_BRAM_21_ECC_ONOFF_RESET_VALUE 0U
#define XPAR_BRAM_21_WRITE_ACCESS 0U
#define XPAR_BRAM_21_BASEADDR 0xD2000000U
#define XPAR_BRAM_21_HIGHADDR 0xD201FFFFU
#define XPAR_BRAM_21_CTRL_BASEADDR 0xFFFFFFFFU  
#define XPAR_BRAM_21_CTRL_HIGHADDR 0xFFFFFFFEU  

/* Canonical definitions for peripheral MICROBLAZE_0_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR */
#define XPAR_BRAM_22_DEVICE_ID XPAR_MICROBLAZE_0_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_DEVICE_ID
#define XPAR_BRAM_22_DATA_WIDTH 32U
#define XPAR_BRAM_22_ECC 0U
#define XPAR_BRAM_22_FAULT_INJECT 0U
#define XPAR_BRAM_22_CE_FAILING_REGISTERS 0U
#define XPAR_BRAM_22_UE_FAILING_REGISTERS 0U
#define XPAR_BRAM_22_ECC_STATUS_REGISTERS 0U
#define XPAR_BRAM_22_CE_COUNTER_WIDTH 0U
#define XPAR_BRAM_22_ECC_ONOFF_REGISTER 0U
#define XPAR_BRAM_22_ECC_ONOFF_RESET_VALUE 1U
#define XPAR_BRAM_22_WRITE_ACCESS 2U
#define XPAR_BRAM_22_BASEADDR 0x00000000U
#define XPAR_BRAM_22_HIGHADDR 0x000FFFFFU
#define XPAR_BRAM_22_CTRL_BASEADDR 0xFFFFFFFFU  
#define XPAR_BRAM_22_CTRL_HIGHADDR 0xFFFFFFFEU  

/* Canonical definitions for peripheral MICROBLAZE_0_LOCAL_MEMORY_ILMB_BRAM_IF_CNTLR */
#define XPAR_BRAM_23_DEVICE_ID XPAR_MICROBLAZE_0_LOCAL_MEMORY_ILMB_BRAM_IF_CNTLR_DEVICE_ID
#define XPAR_BRAM_23_DATA_WIDTH 32U
#define XPAR_BRAM_23_ECC 0U
#define XPAR_BRAM_23_FAULT_INJECT 0U
#define XPAR_BRAM_23_CE_FAILING_REGISTERS 0U
#define XPAR_BRAM_23_UE_FAILING_REGISTERS 0U
#define XPAR_BRAM_23_ECC_STATUS_REGISTERS 0U
#define XPAR_BRAM_23_CE_COUNTER_WIDTH 0U
#define XPAR_BRAM_23_ECC_ONOFF_REGISTER 0U
#define XPAR_BRAM_23_ECC_ONOFF_RESET_VALUE 1U
#define XPAR_BRAM_23_WRITE_ACCESS 2U
#define XPAR_BRAM_23_BASEADDR 0x00000000U
#define XPAR_BRAM_23_HIGHADDR 0x000FFFFFU
#define XPAR_BRAM_23_CTRL_BASEADDR 0xFFFFFFFFU  
#define XPAR_BRAM_23_CTRL_HIGHADDR 0xFFFFFFFEU  


/******************************************************************/

/* Definitions for driver TMRCTR */
#define XPAR_XTMRCTR_NUM_INSTANCES 1U

/* Definitions for peripheral AXI_TIMER_0 */
#define XPAR_AXI_TIMER_0_DEVICE_ID 0U
#define XPAR_AXI_TIMER_0_BASEADDR 0x41C00000U
#define XPAR_AXI_TIMER_0_HIGHADDR 0x41C0FFFFU
#define XPAR_AXI_TIMER_0_CLOCK_FREQ_HZ 100000000U


/******************************************************************/

/* Canonical definitions for peripheral AXI_TIMER_0 */
#define XPAR_TMRCTR_0_DEVICE_ID 0U
#define XPAR_TMRCTR_0_BASEADDR 0x41C00000U
#define XPAR_TMRCTR_0_HIGHADDR 0x41C0FFFFU
#define XPAR_TMRCTR_0_CLOCK_FREQ_HZ XPAR_AXI_TIMER_0_CLOCK_FREQ_HZ

/******************************************************************/

/* Definitions for driver UARTLITE */
#define XPAR_XUARTLITE_NUM_INSTANCES 1U

/* Definitions for peripheral AXI_UARTLITE_0 */
#define XPAR_AXI_UARTLITE_0_DEVICE_ID 0U
#define XPAR_AXI_UARTLITE_0_BASEADDR 0x40600000U
#define XPAR_AXI_UARTLITE_0_HIGHADDR 0x4060FFFFU
#define XPAR_AXI_UARTLITE_0_BAUDRATE 9600U
#define XPAR_AXI_UARTLITE_0_USE_PARITY 0U
#define XPAR_AXI_UARTLITE_0_ODD_PARITY 0U
#define XPAR_AXI_UARTLITE_0_DATA_BITS 8U

/* Canonical definitions for peripheral AXI_UARTLITE_0 */
#define XPAR_UARTLITE_0_DEVICE_ID 0U
#define XPAR_UARTLITE_0_BASEADDR 0x40600000U
#define XPAR_UARTLITE_0_HIGHADDR 0x4060FFFFU
#define XPAR_UARTLITE_0_BAUDRATE 9600U
#define XPAR_UARTLITE_0_USE_PARITY 0U
#define XPAR_UARTLITE_0_ODD_PARITY 0U
#define XPAR_UARTLITE_0_DATA_BITS 8U


/******************************************************************/
#endif  /* end of protection macro */
